name: Lambda Load Test

on:
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./load-test

      - name: Run Artillery Load Test & Collect Metrics
        run: |
          npm run test
          node collect-metrics.js
        working-directory: ./load-test

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: load-test-reports
          path: |
            ./load-test/artillery-report.html
            ./load-test/artillery-report.json
            ./load-test/cloudwatch-metrics.json
